### ISSUE TITLE
trial._trial_id or trial._number

### ISSUE THREAD

**Issue by hoopwoop** [neptune-ai/neptune-optuna#45]
Hi, I'm using the neptune-optuna integration, and I found the numbering in neptuna a bit confusing. Shouldn't the  trial._trial_id (counted in the database across studies, which does not start from 0 when initializing a new study) in the _log_single_trial method be replaced with trial._number (counted only in a study, starts from 0 when initializing a new study) ?

https://github.com/neptune-ai/neptune-optuna/blob/546181787d4c4cb13fa6bb6ff285778ede33d2b4/src/neptune_optuna/impl/__init__.py#L594

**Comment by SiddhantSadangi** [comment]
Hey @hoopwoop 👋 

Nice observation! Since most of our users use `InMemoryStorage`, this never seemed to be an issue as trial IDs would start from 0 for each new study, but I can imagine this not being the case for persistent storage (although I haven't tested it yet).

Are you using persistent storage to store Optuna studies? If so, could you send me a screenshot of what the `trials` folder looks like in the Neptune run? Feel free to drop a mail to support@neptune.ai if you don't want to share it in public.

I am leaving on a 3-week vacation starting tomorrow, but replacing `_trial_id` with `_number` should be pretty straightforward. You can update your local source code for the time being, and I will implement the changes in a new release of `neptune-optuna` once I am back.

**Comment by hoopwoop** [comment]
Hi @SiddhantSadangi,

Yes, I'm using a persistent storage, and please see image below.
![image](https://github.com/user-attachments/assets/cb6ef29f-482a-4e75-a5f8-5145db17853d)

I've solved it by using `_number` in my code. Would be happy to use that coming update. Thx!

**Comment by SiddhantSadangi** [comment]
Hey @hoopwoop 👋 

We've fixed this in the [1.4.0 release](https://github.com/neptune-ai/neptune-optuna/releases/tag/1.4.0) 🎉 

Can you update `neptune-optuna` to the latest version and let me know if it works for you? 🙏
